title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"

# style: minimal             # use a simpler style inspired by the minima theme
hide_title: false            # remove site heading in the header
hide_footer: true            # hide the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark

navigation:                  # site navigation in the header
  - index.html
  - README.md
#  - title: "https://"       # linking external sites is also supported

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
